# Generated by Django 6.0.5 on 2026-06-03 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibition',
            options={'verbose_name': 'Выставка', 'verbose_name_plural': 'Выставки'},
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='curator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibitions', to=settings.AUTH_USER_MODEL, verbose_name='Куратор'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='photos_count',
            field=models.IntegerField(verbose_name='Количество фото'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Название выставки'),
        ),
    ]
