# Generated by Django 6.0.5 on 2026-06-04 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0005_exhibitioncomment_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhibitions', to=settings.AUTH_USER_MODEL, verbose_name='Куратор'),
        ),
        migrations.CreateModel(
            name='ExhibitionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='Guest', max_length=80, verbose_name='Имя автора')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('rating', models.IntegerField(choices=[(1, '1 — не зацепило'), (2, '2 — слабовато'), (3, '3 — нормально'), (4, '4 — атмосферно'), (5, '5 — очень вайбово')], verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhibition_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='exhibitions.exhibition', verbose_name='Выставка')),
            ],
            options={
                'verbose_name': 'Комментарий к выставке',
                'verbose_name_plural': 'Комментарии к выставкам',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ExhibitionComment',
        ),
    ]
