# Generated by Django 6.0.5 on 2026-06-05 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0006_alter_exhibition_curator_exhibitionreview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='photos_count',
        ),
        migrations.CreateModel(
            name='ExhibitionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(help_text='Путь сохраняется автоматически после загрузки файла.', max_length=500, verbose_name='Путь к картинке')),
                ('caption', models.CharField(blank=True, max_length=160, verbose_name='Подпись')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Позиция')),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='exhibitions.exhibition', verbose_name='Выставка')),
            ],
            options={
                'verbose_name': 'Фотография выставки',
                'verbose_name_plural': 'Фотографии выставок',
                'ordering': ['position', 'id'],
            },
        ),
    ]
