# Generated by Django 6.0.5 on 2026-06-03 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'verbose_name': 'Камера', 'verbose_name_plural': 'Камеры'},
        ),
        migrations.AlterModelOptions(
            name='camerabrand',
            options={'verbose_name': 'Бренд камеры', 'verbose_name_plural': 'Бренды камер'},
        ),
        migrations.AlterField(
            model_name='camera',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='cameras.camerabrand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='is_rare',
            field=models.BooleanField(default=False, verbose_name='Редкая'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='is_working',
            field=models.BooleanField(default=True, verbose_name='Рабочая'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Название камеры'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='year',
            field=models.IntegerField(verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='camerabrand',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='camerabrand',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название бренда'),
        ),
    ]
