# Generated by Django 6.0.5 on 2026-06-03 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_alter_camera_options_alter_camerabrand_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(choices=[(1, '1 — плохо'), (2, '2 — слабо'), (3, '3 — нормально'), (4, '4 — хорошо'), (5, '5 — отлично')], verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cameras.camera', verbose_name='Камера')),
            ],
            options={
                'verbose_name': 'Отзыв о камере',
                'verbose_name_plural': 'Отзывы о камерах',
                'ordering': ['-created_at'],
            },
        ),
    ]
