# Generated by Django 6.0.5 on 2026-06-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_camerareview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camerareview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комментарий к камере', 'verbose_name_plural': 'Комментарии к камерам'},
        ),
        migrations.RemoveField(
            model_name='camerareview',
            name='author',
        ),
        migrations.AddField(
            model_name='camerareview',
            name='author_name',
            field=models.CharField(default='Гость', max_length=80, verbose_name='Имя автора'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camerareview',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 — не зацепило'), (2, '2 — слабовато'), (3, '3 — нормально'), (4, '4 — атмосферно'), (5, '5 — очень вайбово')], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='camerareview',
            name='text',
            field=models.TextField(verbose_name='Комментарий'),
        ),
    ]
