# Generated by Django 6.0.5 on 2026-06-04 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0005_camerareview_author_alter_camerareview_author_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to=settings.AUTH_USER_MODEL, verbose_name='Автор записи'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cameras', to='cameras.camerabrand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='camerareview',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
