# Generated by Django 6.0.5 on 2026-06-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0006_camera_owner_alter_camera_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='image_path',
            field=models.CharField(blank=True, help_text='Путь сохраняется автоматически после загрузки файла.', max_length=500, verbose_name='Фото камеры'),
        ),
    ]
