# Generated by Django 6.0.5 on 2026-06-03 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preset',
            options={'verbose_name': 'Пресет', 'verbose_name_plural': 'Пресеты'},
        ),
        migrations.AlterField(
            model_name='preset',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presets', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='preset',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='preset',
            name='intensity',
            field=models.IntegerField(verbose_name='Интенсивность'),
        ),
        migrations.AlterField(
            model_name='preset',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Открытый'),
        ),
        migrations.AlterField(
            model_name='preset',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Название пресета'),
        ),
        migrations.AlterField(
            model_name='preset',
            name='tone',
            field=models.CharField(max_length=100, verbose_name='Тон'),
        ),
    ]
