# Generated by Django 6.0.5 on 2026-06-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presets', '0006_alter_preset_author_alter_presetreview_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='image_path',
            field=models.CharField(blank=True, help_text='Путь сохраняется автоматически после загрузки файла.', max_length=500, verbose_name='Фото пресета'),
        ),
    ]
